### PR TITLE
1.9 test

### PR DESCRIPTION
**Pull request by UnRealDinnerbone**
TEsting

### CODE REVIEW

**Comment by UnRealDinnerbone** [comment]
Can one of the admins verify this patch?

**Comment by Johnsmith0508** [comment]
there is literally one change to `changelog.txt`. you would have to _try_ to make any conflicts

**Comment by UnRealDinnerbone** [comment]
Im Trying to test something with my Jenkins :package:

**Comment by Johnsmith0508** [comment]
ah, I was wondering why this warranted a pr

**Comment by UnRealDinnerbone** [comment]
And my Jenkins said that Admin thing

**Pull request closed without merging**
